# Generated by Django 4.1.7 on 2023-03-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunr", "0002_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="album",
            field=models.CharField(default="no album title", max_length=255),
        ),
        migrations.AddField(
            model_name="song",
            name="preview_url",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="song",
            name="title",
            field=models.CharField(default="no song title", max_length=255),
        ),
    ]
